- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install packages
      command: pkg_add {{ item }}
      loop:
        - vim-8.2.4600-no_x11-ruby
        - curl
        - zsh
        - ImageMagick
        - alacritty
        - firefox
        - chromium
        - feh
        - ghostwriter
        - hack-fonts
        - picom
        - git
        - doas
        - go
        - rust
        - github-cli
        - terraform
        - ruby-3.1.2
        - ruby-shims
    - name: Install bundler
      command: gem install bundler
